#!/usr/bin/env python3
"""Build final report DOCX, report Markdown, and presentation outline.

The DOCX is generated by reusing the ESOGUmmfSABLON.docx package and replacing
the main document body with project-specific content. Run experiments first so
tables contain the exact metric values used in the presentation.
"""

from __future__ import annotations

import argparse
import datetime as dt
import shutil
import zipfile
from pathlib import Path
from tempfile import TemporaryDirectory
from xml.sax.saxutils import escape

import pandas as pd
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
METRICS_DIR = ROOT / "results" / "metrics"
REPORTS_DIR = ROOT / "reports"
DOCS_DIR = ROOT / "docs"
FIGURES_DIR = ROOT / "results" / "figures"
DEFAULT_TEMPLATE = Path("/Users/erenterakye/Downloads/ESOGUmmfSABLON.docx")


SOURCES = [
    "Prasad, A. ve Chandra, S. (2024). PhiUSIIL: A diverse security profile empowered phishing URL detection framework based on similarity index and incremental learning. Computers & Security, 136, 103545. https://doi.org/10.1016/j.cose.2023.103545",
    "Vajrobol, V., Gupta, B. B. ve Gaurav, A. (2024). Mutual information based logistic regression for phishing URL detection. Cyber Security and Applications, 2, 100044. https://doi.org/10.1016/j.csa.2024.100044",
    "Yoon, J.-H., Buu, S.-J. ve Kim, H.-J. (2024). Phishing Webpage Detection via Multi-Modal Integration of HTML DOM Graphs and URL Features Based on Graph Convolutional and Transformer Networks. Electronics, 13(16), 3344. https://doi.org/10.3390/electronics13163344",
    "Rao, R. S., Kondaiah, C., Pais, A. R. ve Lee, B. (2025). A hybrid super learner ensemble for phishing detection on mobile devices. Scientific Reports. https://doi.org/10.1038/s41598-025-02009-8",
    "Taha, M. A., Jabar, H. D. A. ve Mohammed, W. K. (2024). A Machine Learning Algorithms for Detecting Phishing Websites: A Comparative Study. Iraqi Journal for Computer Science and Mathematics. https://doi.org/10.52866/ijcsm.2024.05.03.015",
    "Kytidou, E., Tsikriki, T., Drosatos, G. ve Rantos, K. (2025). Machine learning techniques for phishing detection: A review of methods, challenges, and future directions. Intelligent Decision Technologies. https://doi.org/10.1177/18724981251366763",
]

REPORT_FIGURES = [
    ("class_distribution.png", "Şekil 1. PhiUSIIL sınıf dağılımı"),
    ("model_metric_comparison.png", "Şekil 2. Deney ve model bazlı metrik karşılaştırması"),
    ("leakage_delta.png", "Şekil 3. Tam özellik seti ile leakage-free sonuçlar arasındaki fark"),
    ("confusion_matrix_leakage_free_best.png", "Şekil 4. Leakage-free en iyi model için karmaşıklık matrisi"),
    ("roc_curves_leakage_free.png", "Şekil 5. Leakage-free deney ROC eğrileri"),
    ("feature_importance_rf_top20.png", "Şekil 6. Random Forest Top-20 özellik önemleri"),
]


def read_metrics() -> dict[str, pd.DataFrame]:
    required = {
        "full": "experiment_1_full_features.csv",
        "vajrobol": "experiment_2_vajrobol_5.csv",
        "rf_top20": "experiment_3_rf_top20.csv",
        "clean": "experiment_4_leakage_free.csv",
        "delta": "leakage_delta.csv",
        "literature": "literature_comparison.csv",
    }
    missing = [name for name in required.values() if not (METRICS_DIR / name).exists()]
    if missing:
        raise FileNotFoundError(
            "Run scripts/run_final_experiments.py first. Missing metrics: " + ", ".join(missing)
        )
    return {key: pd.read_csv(METRICS_DIR / filename) for key, filename in required.items()}


def fmt_pct(value) -> str:
    if pd.isna(value):
        return "-"
    return f"{float(value) * 100:.2f}%"


def fmt_num(value) -> str:
    if pd.isna(value):
        return "-"
    return f"{float(value):.4f}"


def top_row(df: pd.DataFrame) -> pd.Series:
    return df.sort_values(["F1-Score", "Recall"], ascending=False).iloc[0]


def metric_table(df: pd.DataFrame) -> list[list[str]]:
    cols = ["Model", "Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC", "Train Time (s)"]
    rows = [cols]
    for _, row in df[cols].iterrows():
        rows.append(
            [
                str(row["Model"]),
                fmt_pct(row["Accuracy"]),
                fmt_pct(row["Precision"]),
                fmt_pct(row["Recall"]),
                fmt_pct(row["F1-Score"]),
                fmt_num(row["ROC-AUC"]),
                f"{float(row['Train Time (s)']):.2f}",
            ]
        )
    return rows


def build_sections(metrics: dict[str, pd.DataFrame]) -> list[dict]:
    best_clean = top_row(metrics["clean"])
    best_full = top_row(metrics["full"])
    lr_vaj = metrics["vajrobol"][metrics["vajrobol"]["Model"] == "Logistic Regression"].iloc[0]

    sections: list[dict] = [
        {"type": "title", "text": "Makine Ogrenmesi ile Phishing URL Tespiti: Leakage-Aware PhiUSIIL Analizi"},
        {
            "type": "paragraph",
            "text": "Eren Terakye ve proje grubu, Eskisehir Osmangazi Universitesi Bilgisayar Muhendisligi Bolumu",
        },
        {"type": "heading", "level": 1, "text": "Oz"},
        {
            "type": "paragraph",
            "text": (
                "Bu calismada PhiUSIIL Phishing URL veri seti uzerinde klasik makine ogrenmesi "
                "algoritmalari karsilastirilmis ve veri seti yapisindan kaynaklanabilecek etiket "
                "sizintisi deneysel olarak incelenmistir. Logistic Regression, Decision Tree, "
                "Random Forest, XGBoost, SVM ve KNN modelleri tam ozellik seti, Vajrobol-5, RF Top-20 "
                "ve leakage-free ozellik setleri ile degerlendirilmistir. Leakage-free deneyde en iyi "
                f"model {best_clean['Model']} olmus; accuracy {fmt_pct(best_clean['Accuracy'])}, "
                f"recall {fmt_pct(best_clean['Recall'])}, F1-score {fmt_pct(best_clean['F1-Score'])} "
                f"ve ROC-AUC {fmt_num(best_clean['ROC-AUC'])} elde edilmistir. Bulgular, tam ozellik "
                "setindeki cok yuksek sonuclarin bir bolumunun sızıntılı ozelliklerden etkilendigini "
                "gostermektedir."
            ),
        },
        {"type": "heading", "level": 1, "text": "Abstract"},
        {
            "type": "paragraph",
            "text": (
                "This study compares classical machine learning algorithms on the PhiUSIIL Phishing URL "
                "dataset and evaluates the effect of construction-time label leakage. Logistic Regression, "
                "Decision Tree, Random Forest, XGBoost, SVM, and KNN are tested under full-feature, "
                "Vajrobol-5, RF Top-20, and leakage-free settings. The leakage-free setting provides a more "
                "defensible estimate of real-world model behavior."
            ),
        },
        {"type": "heading", "level": 1, "text": "1. Giris"},
        {
            "type": "paragraph",
            "text": (
                "Phishing saldirilari kullanicilari sahte web sayfalari veya URL'ler uzerinden kandirarak "
                "kimlik bilgileri, finansal veriler ve kurumsal hesaplar icin ciddi risk olusturur. URL "
                "tabanli tespit yaklasimlari, kullanici tarafinda hizli karar verebildigi icin pratik bir "
                "savunma katmani sunar. Ancak literaturde raporlanan cok yuksek basarim degerleri, veri "
                "setinin toplanma ve ozellik uretme sureci nedeniyle dikkatli yorumlanmalidir."
            ),
        },
        {
            "type": "paragraph",
            "text": (
                "Bu calismanin amaci yalnizca en yuksek accuracy degerini elde etmek degildir. Ana katkı, "
                "PhiUSIIL veri setinde sızıntılı olabilecek ozelliklerin etkisini ayirarak modellerin daha "
                "gercekci kosullarda nasil davrandigini gostermektir."
            ),
        },
        {"type": "heading", "level": 1, "text": "2. Bilimsel Yazin Taramasi"},
        {
            "type": "paragraph",
            "text": (
                "Prasad ve Chandra (2024), PhiUSIIL veri setini ve similarity index ile desteklenen "
                "incremental learning yaklasimini tanitmistir. Vajrobol ve diğ. (2024), mutual information "
                "ile secilen bes ozellik ve Logistic Regression kullanarak cok yuksek basarim raporlamistir. "
                "Yoon ve diğ. (2024) URL, HTML ve graf temsillerini derin ogrenme mimarileriyle birlestirmis; "
                "Rao ve diğ. (2025) mobil senaryo icin Super Learner ensemble onermistir. Taha ve diğ. (2024) "
                "klasik ML modellerini daha kucuk bir phishing veri setinde karsilastirmistir. Kytidou ve diğ. "
                "(2025) ise veri seti kalitesi, concept drift ve aciklanabilirlik sorunlarini phishing tespitinin "
                "temel acik problemleri arasinda tartismistir."
            ),
        },
        {
            "type": "table",
            "caption": "Tablo 1. Literatür ve Bu Çalışmanın Karşılaştırılması",
            "rows": literature_table(metrics["literature"]),
        },
        {"type": "heading", "level": 1, "text": "3. Yontem"},
        {
            "type": "paragraph",
            "text": (
                "Veri seti 235.795 URL orneginden olusmaktadir. Hedef degisken label sutunudur; 1 mesru, "
                "0 phishing URL anlamina gelir. FILENAME, URL, Domain ve Title tanimlayici sutunlari model "
                "egitiminden cikarilmistir. TLD kategorik degiskeni egitim verisine gore encode edilmis, "
                "sayisal ozellikler StandardScaler ile yalnizca egitim setine fit edilerek olceklendirilmistir. "
                "Train/test ayrimi stratified 80/20 ve random_state=42 ile yapilmistir."
            ),
        },
        {
            "type": "paragraph",
            "text": (
                "Dort deney tanimlanmistir: tam ozellik seti, Vajrobol-5 ozellikleri, Random Forest Top-20 "
                "ozellikleri ve leakage-free ozellik seti. Leakage-free deneyde URLSimilarityIndex, URLCharProb, "
                "TLDLegitimateProb ve URLTitleMatchScore cikarilmistir. Bu ozellikler veri seti olusturulurken "
                "mesru URL listesi veya mesru site istatistikleri ile iliskili oldugu icin etikete yakin vekil "
                "degiskenler gibi davranabilir."
            ),
        },
        {"type": "heading", "level": 1, "text": "4. Bulgular"},
        {
            "type": "paragraph",
            "text": (
                f"Tam ozellik setinde en iyi model {best_full['Model']} olmus ve accuracy "
                f"{fmt_pct(best_full['Accuracy'])} olarak olculmustur. Vajrobol-5 replikasyonunda Logistic "
                f"Regression accuracy degeri {fmt_pct(lr_vaj['Accuracy'])} seviyesine ulasmistir. Ancak "
                "leakage-free deney, bu yuksek degerlerin gercek dunya genellenebilirligini tek basina "
                "garanti etmedigini gostermektedir."
            ),
        },
        {"type": "table", "caption": "Tablo 2. Tam Özellik Seti Sonuçları", "rows": metric_table(metrics["full"])},
        {"type": "table", "caption": "Tablo 3. Vajrobol-5 Replikasyon Sonuçları", "rows": metric_table(metrics["vajrobol"])},
        {"type": "table", "caption": "Tablo 4. RF Top-20 Sonuçları", "rows": metric_table(metrics["rf_top20"])},
        {"type": "table", "caption": "Tablo 5. Leakage-Free Sonuçlar", "rows": metric_table(metrics["clean"])},
        {"type": "table", "caption": "Tablo 6. Sızıntı Etkisi: Tam Özellik - Leakage-Free", "rows": delta_table(metrics["delta"])},
        *[
            {"type": "figure", "path": FIGURES_DIR / filename, "caption": caption}
            for filename, caption in REPORT_FIGURES
        ],
        {"type": "heading", "level": 1, "text": "5. Tartisma"},
        {
            "type": "paragraph",
            "text": (
                "Sonuclar iki katmanli yorumlanmalidir. Ilk katmanda, PhiUSIIL uzerindeki klasik makine "
                "ogrenmesi modelleri yuksek ayirt edicilik gostermektedir. Ikinci katmanda, bazi ozelliklerin "
                "veri seti insa sureciyle iliskili olmasi model basarimini sisirebilir. Bu nedenle tam ozellik "
                "seti literaturle karsilastirma icin yararli, leakage-free deney ise uygulama davranisini "
                "tartismak icin daha guvenilir kabul edilmelidir."
            ),
        },
        {"type": "heading", "level": 1, "text": "6. Sonuclar"},
        {
            "type": "paragraph",
            "text": (
                "Bu calismada PhiUSIIL veri seti uzerinde alti makine ogrenmesi modeli sistematik olarak "
                "karsilastirilmis, literaturdeki Vajrobol-5 bulgusu yeniden denenmis ve sızıntılı ozelliklerin "
                "etkisi deneysel olarak ayrilmistir. Literatürdeki kaynaklardan farkli olarak bu calisma, "
                "yalnizca yuksek dogruluk raporlamak yerine ayni veri setindeki potansiyel construction-time "
                "leakage etkisini acikca gosterir ve temiz ozellik setiyle daha savunulabilir bir performans "
                "degerlendirmesi sunar."
            ),
        },
        {
            "type": "paragraph",
            "text": (
                "Gelecek calismalarda zaman bazli ayrim, farkli kaynaklardan toplanmis dis test seti, esik "
                "optimizasyonu ve SHAP/LIME gibi aciklanabilirlik yontemleriyle model davranisi daha ayrintili "
                "incelenebilir."
            ),
        },
        {"type": "heading", "level": 1, "text": "Araştırma ve Yayın Etiği"},
        {
            "type": "paragraph",
            "text": (
                "Bu çalışma açık erişimli veri seti ve literatür kaynakları kullanılarak hazırlanmıştır. "
                "Literatürden alınan bilgiler sentezlenmiş, metin öğrencilerin kendi cümleleriyle yazılmıştır."
            ),
        },
        {"type": "heading", "level": 1, "text": "Çıkar Çatışması"},
        {"type": "paragraph", "text": "Yazarlar tarafından herhangi bir çıkar çatışması beyan edilmemiştir."},
        {"type": "heading", "level": 1, "text": "NOT"},
        {
            "type": "paragraph",
            "text": "Bu proje başka bir derste proje olarak kullanılmamıştır ve kullanılması planlanmamaktadır.",
        },
        {"type": "heading", "level": 1, "text": "Kaynaklar"},
    ]

    for source in SOURCES:
        sections.append({"type": "paragraph", "text": source})
    return sections


def literature_table(df: pd.DataFrame) -> list[list[str]]:
    rows = [["Kaynak", "Yontem", "Veri Seti", "Accuracy", "F1", "Recall", "Not"]]
    for _, row in df.iterrows():
        rows.append(
            [
                str(row["Kaynak"]),
                str(row["Yontem"]),
                str(row["Veri Seti"]),
                fmt_pct(row["Accuracy"]),
                fmt_pct(row["F1-Score"]),
                fmt_pct(row["Recall"]),
                str(row["Not"]),
            ]
        )
    return rows


def delta_table(df: pd.DataFrame) -> list[list[str]]:
    rows = [["Model", "Accuracy Delta", "Recall Delta", "F1 Delta"]]
    for _, row in df.iterrows():
        rows.append(
            [
                str(row["Model"]),
                fmt_num(row["Accuracy"]),
                fmt_num(row["Recall"]),
                fmt_num(row["F1-Score"]),
            ]
        )
    return rows


def markdown_from_sections(sections: list[dict]) -> str:
    lines = []
    for section in sections:
        stype = section["type"]
        if stype == "title":
            lines.append(f"# {section['text']}\n")
        elif stype == "heading":
            level = "#" * (section["level"] + 1)
            lines.append(f"{level} {section['text']}\n")
        elif stype == "paragraph":
            lines.append(section["text"] + "\n")
        elif stype == "table":
            lines.append(f"**{section['caption']}**\n")
            rows = section["rows"]
            header = rows[0]
            lines.append("| " + " | ".join(header) + " |")
            lines.append("| " + " | ".join(["---"] * len(header)) + " |")
            for row in rows[1:]:
                lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
            lines.append("")
        elif stype == "figure":
            rel_path = Path("..") / section["path"].relative_to(ROOT)
            lines.append(f"![{section['caption']}]({rel_path})\n")
            lines.append(f"*{section['caption']}*\n")
    return "\n".join(lines).strip() + "\n"


def p_xml(text: str, style: str | None = None, bold: bool = False) -> str:
    style_xml = f'<w:pPr><w:pStyle w:val="{style}"/></w:pPr>' if style else ""
    bold_xml = "<w:b/>" if bold else ""
    return (
        "<w:p>"
        f"{style_xml}"
        "<w:r>"
        f"<w:rPr>{bold_xml}</w:rPr>"
        f"<w:t xml:space=\"preserve\">{escape(text)}</w:t>"
        "</w:r>"
        "</w:p>"
    )


def table_xml(rows: list[list[str]]) -> str:
    max_cols = max(len(r) for r in rows)
    grid = "".join('<w:gridCol w:w="2200"/>' for _ in range(max_cols))
    xml = [
        "<w:tbl>",
        '<w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="0" w:type="auto"/>'
        '<w:tblLook w:firstRow="1" w:lastRow="0" w:firstColumn="0" w:lastColumn="0" '
        'w:noHBand="0" w:noVBand="1"/></w:tblPr>',
        f"<w:tblGrid>{grid}</w:tblGrid>",
    ]
    for row_i, row in enumerate(rows):
        xml.append("<w:tr>")
        for cell in row:
            shade = '<w:shd w:fill="D9EAF7"/>' if row_i == 0 else ""
            xml.append(
                "<w:tc>"
                f'<w:tcPr><w:tcW w:w="2200" w:type="dxa"/>{shade}</w:tcPr>'
                f"{p_xml(str(cell), bold=(row_i == 0))}"
                "</w:tc>"
            )
        xml.append("</w:tr>")
    xml.append("</w:tbl>")
    return "".join(xml)


def image_xml(rid: str, image_id: int, width_emu: int, height_emu: int) -> str:
    return f"""
<w:p>
  <w:r>
    <w:drawing>
      <wp:inline xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" distT="0" distB="0" distL="0" distR="0">
        <wp:extent cx="{width_emu}" cy="{height_emu}"/>
        <wp:effectExtent l="0" t="0" r="0" b="0"/>
        <wp:docPr id="{image_id}" name="Project Figure {image_id}"/>
        <wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1"/></wp:cNvGraphicFramePr>
        <a:graphic>
          <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
            <pic:pic>
              <pic:nvPicPr>
                <pic:cNvPr id="{image_id}" name="Project Figure {image_id}"/>
                <pic:cNvPicPr/>
              </pic:nvPicPr>
              <pic:blipFill>
                <a:blip r:embed="{rid}"/>
                <a:stretch><a:fillRect/></a:stretch>
              </pic:blipFill>
              <pic:spPr>
                <a:xfrm><a:off x="0" y="0"/><a:ext cx="{width_emu}" cy="{height_emu}"/></a:xfrm>
                <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
              </pic:spPr>
            </pic:pic>
          </a:graphicData>
        </a:graphic>
      </wp:inline>
    </w:drawing>
  </w:r>
</w:p>
"""


def body_xml(sections: list[dict], sect_pr: str, image_map: dict[str, tuple[str, int, int, int]]) -> str:
    body_parts = []
    for section in sections:
        stype = section["type"]
        if stype == "title":
            body_parts.append(p_xml(section["text"], "Title", bold=True))
        elif stype == "heading":
            style = "Heading1" if section["level"] == 1 else "Heading2"
            body_parts.append(p_xml(section["text"], style, bold=True))
        elif stype == "paragraph":
            body_parts.append(p_xml(section["text"], "Normal"))
        elif stype == "table":
            body_parts.append(p_xml(section["caption"], "Normal", bold=True))
            body_parts.append(table_xml(section["rows"]))
            body_parts.append(p_xml(""))
        elif stype == "figure":
            rid, image_id, width_emu, height_emu = image_map[str(section["path"])]
            body_parts.append(image_xml(rid, image_id, width_emu, height_emu))
            body_parts.append(p_xml(section["caption"], "Normal", bold=True))
    return "".join(body_parts) + sect_pr


def generate_docx(template: Path, out_path: Path, sections: list[dict]) -> None:
    with TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        with zipfile.ZipFile(template) as zin:
            zin.extractall(tmp_path)

        image_map: dict[str, tuple[str, int, int, int]] = {}
        rels_path = tmp_path / "word" / "_rels" / "document.xml.rels"
        rels_xml = rels_path.read_text(encoding="utf-8")
        for idx, section in enumerate([s for s in sections if s["type"] == "figure"], start=1):
            source = Path(section["path"])
            if not source.exists():
                continue
            media_name = f"project_figure_{idx}.png"
            shutil.copy2(source, tmp_path / "word" / "media" / media_name)
            rid = f"rIdProjectFigure{idx}"
            rel = (
                f'<Relationship Id="{rid}" '
                'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" '
                f'Target="media/{media_name}"/>'
            )
            rels_xml = rels_xml.replace("</Relationships>", rel + "</Relationships>")
            with Image.open(source) as im:
                width_px, height_px = im.size
            width_emu = 5_900_000
            height_emu = int(width_emu * height_px / width_px)
            image_map[str(source)] = (rid, idx, width_emu, height_emu)
        rels_path.write_text(rels_xml, encoding="utf-8")

        doc_path = tmp_path / "word" / "document.xml"
        original = doc_path.read_text(encoding="utf-8")
        body_start = original.index("<w:body>") + len("<w:body>")
        body_end = original.index("</w:body>")
        body = original[body_start:body_end]
        sect_start = body.rfind("<w:sectPr")
        sect_pr = body[sect_start:] if sect_start != -1 else ""
        new_xml = original[:body_start] + body_xml(sections, sect_pr, image_map) + original[body_end:]
        doc_path.write_text(new_xml, encoding="utf-8")

        if out_path.exists():
            out_path.unlink()
        with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zout:
            for path in tmp_path.rglob("*"):
                if path.is_file():
                    zout.write(path, path.relative_to(tmp_path))


def presentation_outline(metrics: dict[str, pd.DataFrame]) -> str:
    best = top_row(metrics["clean"])
    lr_vaj = metrics["vajrobol"][metrics["vajrobol"]["Model"] == "Logistic Regression"].iloc[0]
    today = dt.date(2026, 5, 19).strftime("%d.%m.%Y")
    slides = [
        ("1. Problem ve Motivasyon", "Phishing URL'leri erken tespit etmek; recall odakli degerlendirme."),
        ("2. Veri Seti", "PhiUSIIL: 235.795 URL, 54 sutun, 1=mesru ve 0=phishing."),
        ("3. Literatür Özeti", "Prasad & Chandra, Vajrobol, Yoon, Rao, Taha ve Kytidou calismalari."),
        ("4. Leakage Problemi", "URLSimilarityIndex, URLCharProb, TLDLegitimateProb, URLTitleMatchScore riskli ozellikler."),
        ("5. Deney Protokolü", "Full, Vajrobol-5, RF Top-20, Leakage-Free ve en iyi 3 model icin CV."),
        (
            "6. Model Sonuçları",
            f"Vajrobol-5 LR accuracy: {fmt_pct(lr_vaj['Accuracy'])}; leakage-free en iyi model: {best['Model']}.",
        ),
        (
            "7. Leakage-Free Karşılaştırma",
            f"{best['Model']} leakage-free recall {fmt_pct(best['Recall'])}, F1 {fmt_pct(best['F1-Score'])}.",
        ),
        (
            "8. Literatürden Farkımız",
            "Yuksek skoru tekrar etmek yerine sızıntılı ozellik etkisini deneysel olarak ayirdik.",
        ),
        ("9. Sonuç ve Gelecek Çalışma", "Dis test seti, zaman bazli ayrim, threshold tuning, aciklanabilirlik."),
    ]
    lines = [f"# 21 Mayıs Sunuş Outline\n\nHazırlık tarihi: {today}\n"]
    for title, body in slides:
        lines.append(f"## {title}\n\n{body}\n")
    lines.append(
        "## 10 Dakikalık Video Akışı\n\n"
        "0:00-1:00 problem ve veri seti; 1:00-3:00 literatür ve leakage; "
        "3:00-6:30 deneyler ve metrikler; 6:30-8:30 leakage-free sonuçlar; "
        "8:30-10:00 literatürden farkımız ve sonuç.\n"
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--docx-out", type=Path, default=REPORTS_DIR / "final_report_leakage_aware.docx")
    parser.add_argument("--md-out", type=Path, default=DOCS_DIR / "final_report.md")
    parser.add_argument("--presentation-out", type=Path, default=DOCS_DIR / "final_presentation_outline.md")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    REPORTS_DIR.mkdir(exist_ok=True)
    DOCS_DIR.mkdir(exist_ok=True)

    if not args.template.exists():
        raise FileNotFoundError(f"Template not found: {args.template}")

    metrics = read_metrics()
    sections = build_sections(metrics)
    args.md_out.write_text(markdown_from_sections(sections), encoding="utf-8")
    generate_docx(args.template, args.docx_out, sections)
    args.presentation_out.write_text(presentation_outline(metrics), encoding="utf-8")
    shutil.copy2(args.template, REPORTS_DIR / "ESOGUmmfSABLON_source.docx")

    print(f"Saved {args.md_out.relative_to(ROOT)}")
    print(f"Saved {args.docx_out.relative_to(ROOT)}")
    print(f"Saved {args.presentation_out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
